.PHONY: clean All

All:
	@echo "----------Building project:[ ceaser_decrypt - Debug ]----------"
	@cd "ceaser_decrypt" && "$(MAKE)" -f  "ceaser_decrypt.mk"
clean:
	@echo "----------Cleaning project:[ ceaser_decrypt - Debug ]----------"
	@cd "ceaser_decrypt" && "$(MAKE)" -f  "ceaser_decrypt.mk" clean
